environment:
  JAVA_HOME : C:\Program Files\Java\jdk1.7.0\

install:
  - ps: Start-FileDownload 'http://mirror.symnds.com/software/Apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
  - echo y | 7z x zookeeper-3.4.6.tar.gz  -o"C:\Users\appveyor\"
  - 'C:\Users\appveyor\zookeeper-3.4.6\bin\zkServer.cmd start'
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test
after_test:
  - 'C:\Users\appveyor\zookeeper-3.4.6\bin\zkServer.cmd stop'

build: off